name: d_and_f_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  device_preview: ^1.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.1
  mobile_scanner: ^7.1.3
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true

analyzer:
  exclude:
    - lib/temp/**